#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#include "xparameters.h"

#define PLATFORM_EMAC_BASEADDR XPAR_XEMACPS_0_BASEADDR

// CPU clock frequency macros
#ifndef XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ XPAR_CPU_CORE_CLOCK_FREQ_HZ
#endif

#ifndef XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ
#define XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ XPAR_CPU_CORE_CLOCK_FREQ_HZ
#endif

// Zynq-7000 SCU GIC and Private Timer hardware constants (for new SDT flow compatibility)
#ifndef XPAR_SCUGIC_SINGLE_DEVICE_ID
#define XPAR_SCUGIC_SINGLE_DEVICE_ID 0
#endif

#ifndef XPAR_SCUTIMER_DEVICE_ID
#define XPAR_SCUTIMER_DEVICE_ID 0
#endif

#ifndef XPAR_SCUGIC_0_CPU_BASEADDR
#define XPAR_SCUGIC_0_CPU_BASEADDR XPAR_XSCUGIC_0_BASEADDR
#endif

#ifndef XPAR_SCUGIC_0_DIST_BASEADDR
#define XPAR_SCUGIC_0_DIST_BASEADDR (XPAR_XSCUGIC_0_BASEADDR + 0x1000)
#endif

#ifndef XPAR_SCUTIMER_INTR
#define XPAR_SCUTIMER_INTR 29
#endif

#endif
